Generic/urls.py
from django.urls import path
from Generic.views import *

app_name='Generic'

urlpatterns=[
    path()
]

Specific/urls.py
from django.urls import path
from Specific.views import *

app_name='Specific'

urlpatterns=[
    path('uday/',uday,name='uday'),
    path('venkatesh/',venkatesh,name='venkatesh'),
]

project_13/urls.py
from django.contrib import admin
from django.urls import path,include
from Generic.views import *
import Specific

urlpatterns = [
    path('admin/', admin.site.urls),
    path('me/',me,name='me'),
    path('pavan/',pavan,name='pavan'),


    path('Specific/',include('Specific.urls')),

]

Generic/models.py
from django.db import models

# Create your models here.

Specific/models.py
from django.db import models

# Create your models here.

Generic/views.py
from django.shortcuts import render

# Create your views here.

def me(request):
    return render(request,'me.html')

def pavan(request):
    return render(request,'pavan.html')

Specific/views.py
from django.shortcuts import render

# Create your views here.


def uday(request):
    return render(request,'uday.html')

def venkatesh(request):
    return render(request,'venkatesh.html')

templates/me.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        *
        {
            background-color: rgb(26, 130, 130);
        }
        button
        {
            background-color: orange;
            border-radius: 5px;
        }
        button:hover
        {
            background-color: blueviolet;
            
        }
        h1
        {
           background-color: orange;
        }
        a
        {
            text-decoration:none;
            background-color: orange;
            color: white;
        }
            
    </style>
</head>
<body>
    <center>
        <h2>Hii Ra..</h2>
        <h2>Where are you..??</h2>
        <button><h2><a href="{% url 'pavan' %}">Lover Boy pavan</a></h2></button>
        <button><h2><a href="{% url 'Specific:uday' %}">Waste Fellow Uday</a></h2></button>
        <button><h2><a href="{% url 'Specific:venkatesh' %}">Tiger venkatesh</a></h2></button>


    </center>
    
</body>
</html>

templates/pavan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color:rgb(146, 21, 85) ;">
    <center>
        <h2>Haiii ra...</h2>
        <h2>I am in Office </h2>
        <h2>You....???</h2>
        <button><h2><a href="{% url 'me' %}">Response</a></h2></button>

    </center>
</body>
</html>

templates/uday.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color:rgb(10, 182, 139) ;">
    <center>
        <h1>Haii ra macha...</h1>
        <h2>I am in Room Ra</h2>
        <h2>What about You...??</h2>
        <button><h2><a href="{% url 'me' %}">Response</a></h2></button>

    </center>
    
</body>
</html>

templates/venkatesh.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color:rgb(235, 135, 187) ;">
    <h2>Haii </h2>
    <h2>I am in Duty lo vunna ra</h2>
    <h2> Emm....??</h2>
    <button><h2><a href="{% url 'me' %}">Response</a></h2></button>
</body>
</html>